// <auto-generated />
using System;
using JobBoard.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobBoard.Infrastructure.Migrations
{
    [DbContext(typeof(JobBoardContext))]
    partial class JobBoardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("JobBoard.Core.Entities.JobEntity", b =>
                {
                    b.Property<int>("Job")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2020, 8, 11, 16, 34, 10, 939, DateTimeKind.Local).AddTicks(4660));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnName("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnName("JobTitle")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("Job");

                    b.ToTable("Job");
                });
#pragma warning restore 612, 618
        }
    }
}
